name: sabbeh_clone
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.2+2

environment:
  sdk: '>=2.18.1 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  cubit: ^0.1.2
  flutter_bloc: ^8.1.1
  bloc: ^8.1.0
  audioplayers: ^3.0.1
  flutter_vibrate: ^1.3.0
  firebase_core: ^2.13.1
  firebase_auth: ^4.6.2
  cloud_firestore: ^4.8.0
  equatable: ^2.0.5
  shared_preferences: ^2.0.17
  smooth_page_indicator: ^1.0.1
  modal_progress_hud_nsn: ^0.3.0
  multi_language_json: ^1.2.0
  url_launcher: ^6.1.10
  flutter_native_splash: ^2.2.16
  language_builder: ^0.1.2
#  awesome_notifications: ^0.7.4+1
  background_fetch: ^1.1.6
  flutter_local_notifications: ^14.1.1
  flutter_timezone: ^1.0.6
  device_info_plus: ^9.0.2
#  restart_app: ^1.1.0
#  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.11.0"

flutter_icons:
  android: "sabbeh_icon"
  ios: true
  image_path: "assets/images/sabbeh_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

  flutter_lints: ^2.0.0


flutter_native_splash:
  color: "#000000"
  image: assets/images/sabbeh_splash_logo152.png
#  color_dark: "#000000"
#  image_dark: assets/images/sabbeh_splash_logo152.png
#  android_gravity: center
  android: true
  ios: true
  web: false
  android_12:
    image: assets/images/sabbeh_splash_logo152.png
    color: "#000000"
    icon_background_color: "#000000"
#    image_dark: assets/images/sabbeh_splash_logo152.png
#    color_dark: "#000000"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
#    - assets/langs/
    - assets/sounds/

  fonts:
    - family: GE_SS_Two_Bold
      fonts:
       - asset: assets/fonts/GE_SS_Two_Bold.otf

